### ISSUE TITLE
Installation fails on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by gchadwick** [zanpeeters/QuickLookSIMS#1]
Hi, this looks like a really fantastic tool, would love to use it.  Tried installing on two separate machines running macOS Catalina 10.15.3 and installation failed.   I don't have any idea how to get any information besides what the installer reports, which is essentially nothing:
"The installation failed.
The Installer encountered an error that caused the installation to fail.  Contact the software manufacturer for assistance."
Hope this is an easy fix, a lot of people in our group would enjoy this tool!

**Comment by zanpeeters** [comment]
Thank you for your interest! The error you get is probably due to Catalina's increased security requirements. Installed apps and extensions need to be signed and notarized by Apple. The installer was build on 10.12 Sierra. I am currently on 10.14 Mojave and don't have access to 10.15 Catalina just yet. I'll look into getting QuickLookSIMS updated and notarized.

In the mean time, you can try the following. Try to install. If it fails, go to System Preferences > Security > General. There should be a button Allow Anyway.

If that doesn't work, try [disabling SIP](https://totalfinder.binaryage.com/sip) and/or disabling Gatekeeper (in Terminal type `sudo spctl --master-disable`).

**Comment by gchadwick** [comment]
Thanks a lot for the quick response.  I had to select the "Allow Anyway" option to get the installation processes started, it was just at the very last step in the installer window that it came up with that error saying it failed.  I just realized though that the QuickLook on .im files has somehow been implemented even with that error.  Very strange, but thats all I was hoping for.  Love it!

**Comment by zanpeeters** [comment]
Great to hear that it works!

Just to let you know: the Spotlight plugin (the part that generates Finder info) can take long time to kick in, sometimes a day or more. To help it along, restart your Mac. You can also try to force reindexing of the folder where you store your data as [described here](https://support.apple.com/en-us/HT201716).

**Comment by jsmagyar** [comment]
Just to note the same behavior in MacOS Big Sur 11.0.1... When you click "Allow Anyway" it gives an error message at the very end of the installation...but it seems to have installed at least the QuickLook functionality. Many thanks for a great tool! Fantastically useful!
